#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: <your_assigned_client_id_here>
#            client-secret: <your_assigned_client_secret_here>
#        provider:
#          okta:
#            issuer-uri: https://<your_assigned_subdomain_here>.oktapreview.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-845041.oktapreview.com/oauth2/default
    client-id: 0oauhhqb02oHEW6hE0h7
    client-secret: 8l2TksuETtRUONt8KCaOeshfI_zpEHloqyQa4sHj
